require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'furoshiki' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCPicker', :path => '../node_modules/@react-native-community/picker'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-login-twitter', :path => '../node_modules/react-native-login-twitter'



  # pod 'react-native-cookies', :path => '../node_modules/react-native-cookies'

  target 'furoshikiTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'furoshiki-tvOS' do
  # Pods for furoshiki-tvOS

  target 'furoshiki-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
